# Generated by Django 4.2 on 2023-04-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("can_mark_returned", "Can set book as returned"),),
            },
        ),
    ]
